menu:
- {name: 'people', url: '/people'}
- {name: 'publications', url: '/publications'}
- {name: 'courses', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

people:
- {name: 'Nelly Ng Huei Ying, Nanyang Assistant Professor', url: 'primary-investigator'}
#- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
- {name: 'Marek Gluza, Research Fellow', url: 'research-fellow'}
- {name: 'Ray Ganardi, Research Fellow', url: 'research-fellow'}
- {name: 'Jakub Czartowski, Research Fellow', url: 'research-fellow'}
- {name: 'Jeongrak Son, Graduate Student', url: 'graduate-student'}
- {name: 'Taufiq Murtadho, Graduate Student', url: 'graduate-student'}
- {name: 'Kaiwei Qiu, Graduate Student', url: 'graduate-student'}
- {name: 'Joseph Goo, Project Officer', url: 'project-officer'}
- {name: 'Khanh Uyen Giang, Project Officer', url: 'project-officer'}

- {name: 'Seok Hyung Lie, Alumni, now Asst. Prof. at UNIST, South Korea', title: 'Alumni', url: 'alumni'}
- {name: 'Yu Cai, Alumni, now Quantum Communications Specialist at HSBC', url: 'alumni'}
- {name: 'Khatee Zathul Arifa, now PhD student at University of Wisconsin-Madison', title: 'Alumni, now PhD student at University of Wisconsin-Madison', url: 'alumni'}


courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'google scholar', link: 'https://scholar.google.com/citations?user=ah2xN3IAAAAJ&hl=en&oi=ao'}
- {icon: 'arXiv', link: 'https://arxiv.org/search/?query=nelly+ng&searchtype=all&source=header'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/nelly-ng-58074710b/'}

contacts:
- {name: 'Dr. Academia', title: 'Professor', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/contact.jpg'}
