menu:
- {name: 'people', url: '/people'}
- {name: 'publications', url: '/publications'}
- {name: 'CV', url: '/cv/'}
- {name: 'in.Q gallery', url: '/gallery'}
#- {name: 'courses', url: '/courses'}
#- {name: ' ', url: '/contact'}

people:
- {name: 'Nelly Ng Huei Ying, Nanyang Assistant Professor, CQT Fellow', url: 'primary-investigator'}
#- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
- {name: 'Marek Gluza, Research Fellow, Recipient of Presidential Postdoctoral Fellowship 2022-2024', url: 'research-fellow'}
- {name: 'Ray Ganardi, Research Fellow', url: 'research-fellow'}
- {name: 'Jakub Czartowski, Research Fellow', url: 'research-fellow'}
- {name: 'Jeongrak Son, PhD Student, SINGA scholarship holder', url: 'graduate-student'}
- {name: 'Taufiq Murtadho, PhD Student, Provost scholarship holder', url: 'graduate-student'}
- {name: 'Kaiwei Qiu, PhD Student, NPGS scholarship holder', url: 'graduate-student'}
- {name: 'Zi Yao Lim, PhD Student (co-supervised by Dr. Koh Teck Seng)', url: 'graduate-student'}
- {name: 'Rebecca Chung, Masters Student', url: 'graduate-student'}
- {name: 'Tiang Bi Hong, Project Officer', url: 'project-officer'}
- {name: 'Joseph Goo, Project Officer', url: 'project-officer'}
- {name: 'Khanh Uyen Giang (Kay), Project Officer', url: 'project-officer'}
- {name: 'Xiaoyue Li (Samantha), Project Officer', url: 'project-officer'}
- {name: 'Seok Hyung Lie, Alumni (research fellow), now Asst. Prof. at UNIST, South Korea', title: 'Alumni', url: 'alumni'}
- {name: 'Yu Cai, Alumni (research fellow), now Quantum Communications Specialist at HSBC', url: 'alumni'}
- {name: 'Maria Quadeer, Alumni (research fellow), now research fellow at OIST, Japan', title: 'Alumni', url: 'alumni'}
- {name: 'Khatee Zathul Arifa, Alumni (project officer), now PhD student at University of Wisconsin-Madison', title: 'Alumni, now PhD student at University of Wisconsin-Madison', url: 'alumni'}
- {name: 'Junwoo Jung, Alumni (intern), now student at KAIST, South Korea', title: 'Alumni, now PhD student at University of Wisconsin-Madison', url: 'alumni'}


courses:
#- {name: 'Vector Calculus', url: 'vector-calculus'}
#- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
#- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'google scholar', link: 'https://scholar.google.com/citations?user=ah2xN3IAAAAJ&hl=en&oi=ao'}
- {icon: 'arxiv', link: 'https://arxiv.org/search/?query=nelly+ng&searchtype=all&source=header'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/nelly-ng-58074710b/'}
