menu:
- {name: 'people', url: '/people'}
- {name: 'publications', url: '/publications'}
- {name: 'courses', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

people:
- {name: 'Nelly Ng Huei Ying', title: 'Primary Investigator', email: 'nelly.hy.ng@gmail.com', url: 'primary-investigator'}
#- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
- {name: 'Marek Gluza', title: 'Research Fellow', url: 'research-fellow'}
- {name: 'Ray Ganardi', title: 'Research Fellow', url: 'research-fellow'}
- {name: 'Jakub Czartowski', title: 'Research Fellow', url: 'research-fellow'}
- {name: 'Jeongrak Son', title: 'Graduate student', url: 'graduate-student'}
- {name: 'Taufiq Murtadho', title: 'Graduate student', url: 'graduate-student'}
- {name: 'Kaiwei Qiu', title: 'Graduate student', url: 'graduate-student'}
- {name: 'Joseph Goo', title: 'Project Officer', url: 'project-officer'}
- {name: 'Khanh Uyen Giang', title: 'Project Officer', url: 'project-officer'}

- {name: 'Seok Hyung Lie, Alumni, now Asst. Prof. at UNIST, South Korea', title: 'Alumni', url: 'alumni'}
- {name: 'Yu Cai, Alumni, now Quantum Communications Specialist at HSBC', url: 'alumni'}
- {name: 'Khatee Zathul Arifa', title: 'Alumni, now PhD student at University of Wisconsin-Madison', url: 'alumni'}


courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/LeNPaul'}
- {icon: 'twitter', link: 'https://twitter.com/paululele'}
- {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/lenpaul'}

contacts:
- {name: 'Dr. Academia', title: 'Professor', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/contact.jpg'}
